import Head from "next/head";
import { createGlobalStyle } from "styled-components";

// sections
import Start from '../sections/start'

const GlobalStyle = createGlobalStyle`
	body {
		background: #111133;
	}
	* {
		padding: 0;
		margin: 0;
		box-sizing: border-box;
	}
	a {
		color: inherit;
		text-decoration: none;
	}
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
			<Start />
    </div>
  );
}
